### ISSUE TITLE
How to get startid from AuditRecordsRequest response

### ISSUE THREAD

**Issue by vagarwal77** [mdsol/rwslib#121]
https://rwslib.readthedocs.io/en/latest/odm_adapter.html#auditrecordsrequest-project-name-environment-name

audits = r.send_request(AuditRecordsRequest('MEDIFLEX','DEV'))

I don't see a way to get startid which can be used with subsequent AuditRecordsRequest calls. Please suggest how to get startid value which is (startid=1 | The audit ID to start on. Defaults to 1. The first Audit ID)

Sample response of audits - 

<ODM ODMVersion="1.3" FileType="Transactional" FileOID="de154afa-92ef-417f-bc3a-42691d34f738" CreationDateTime="2021-07-01T18:27:08" xmlns="http://www.cdisc.org/ns/odm/v1.3" xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata">
  <ClinicalData StudyOID="MM-001Test(DEV)" MetaDataVersionOID="235" mdsol:AuditSubCategoryName="SubjectCreated">
    <SubjectData SubjectKey="ddddddd-9e26-4b30-ab19-67665ff96907" mdsol:SubjectKeyType="SubjectUUID" mdsol:SubjectName="001" TransactionType="Upsert">
      <AuditRecord>
        <UserRef UserOID="xxxxxxx" />
        <LocationRef LocationOID="00000" mdsol:StudyEnvSiteNumber="001" />
        <DateTimeStamp>2020-09-24T16:19:49</DateTimeStamp>
        <ReasonForChange></ReasonForChange>
        <SourceID>6781448</SourceID>
      </AuditRecord>
      <SiteRef LocationOID="00000" mdsol:StudyEnvSiteNumber="001" />
    </SubjectData>
  </ClinicalData>
  <ClinicalData StudyOID="Test(DEV)" MetaDataVersionOID="235" mdsol:AuditSubCategoryName="Entered">
    <SubjectData SubjectKey="wewewew-9e26-4b30-ab19-67665ff96907" mdsol:SubjectKeyType="SubjectUUID" mdsol:SubjectName="001">
      <SiteRef LocationOID="00000" mdsol:StudyEnvSiteNumber="001" />
      <StudyEventData StudyEventOID="SUBJECT">
        <FormData FormOID="SUBJECT" FormRepeatKey="1" mdsol:DataPageId="37329">
          <ItemGroupData ItemGroupOID="SUBJECT" mdsol:RecordId="60627">
            <ItemData ItemOID="SUBJECT.SUBJID" TransactionType="Upsert" Value="001">
              <AuditRecord>
                <UserRef UserOID="xxxxxxx" />
                <LocationRef LocationOID="00000" mdsol:StudyEnvSiteNumber="001" />
                <DateTimeStamp>2020-09-24T16:19:49</DateTimeStamp>
                <ReasonForChange></ReasonForChange>
                <SourceID>6781449</SourceID>
              </AuditRecord>
            </ItemData>
          </ItemGroupData>
        </FormData>
      </StudyEventData>
    </SubjectData>
  </ClinicalData>

**Comment by isparks** [comment]
This is actually in the example but could be pointed out better maybe. You're looking for the "Link" in the last_request.headers:

```
>>> audits = r.send_request(AuditRecordsRequest('MEDIFLEX','DEV'))
>>> r.last_request.headers["Link]
https://innovate.mdsol.com/RaveWebServices/datasets/ClinicalAuditRecords.odm?studyoid=MEDIFLEX%28DEV%29&startid=3842&per_page=1000>; rel="next"'
```
The startid is in that response (3842). You have to parse it yourself to get that value. There is some code in audit event which you could steal for this:

```
from urllib.parse import urlparse, parse_qs
result = rws.send_request(AuditRecordsRequest('TG_TEST','Dev'))

link = rws.last_result.links.get("next", None)
if link:
    link = link['url']
    p = urlparse(link)
    start_id = int(parse_qs(p.query)['startid'][0])
    print(start_id)
```

**Comment by glow-mdsol** [comment]
This seems ok to close
