### ISSUE TITLE
rwslib API endpoint to send the audit logs to rave

### ISSUE THREAD

**Issue by vagarwal77** [mdsol/rwslib#122]
We have a use case to push eCRF audit logs from application to Rave.

Is there any rwslib API endpoint to send the audit logs to rave?

**Comment by isparks** [comment]
You can use PostClinicalData:

https://rwslib.readthedocs.io/en/latest/post_clinical_data.html

And include AuditRecords:

https://rwslib.readthedocs.io/en/latest/classes_builders.html?highlight=AuditRecord#medidata-extensions-to-odm-modm-builders

But I can't say I have any experience of doing this. I am not sure if you can push only AuditRecords or if you have to push changes to the data as well as the audit records. And sorry, I don't have any example. @rsayer-mdsol might be able to tell you more.

**Comment by glow-mdsol** [comment]
I can confirm this works as documented, closing
