### ISSUE TITLE
rwslib API endpoint to freeze and lock CRF field to rave

### ISSUE THREAD

**Issue by vagarwal77** [mdsol/rwslib#123]
I am looking for rwslib API endpoint to freeze and lock eCRF fields.. please suggest as i could not found any @ https://rwslib.readthedocs.io/en/latest/index.html

![image](https://user-images.githubusercontent.com/46463536/124212896-b9741a00-dabd-11eb-9bbe-d7fb26cdfe27.png)

**Comment by isparks** [comment]
PostODMData with ItemData element with mdsol:freeze or mdsol:lock set:

https://rwslib.readthedocs.io/en/latest/classes_builders.html?highlight=freeze#rwslib.builders.clinicaldata.ItemData

**Comment by glow-mdsol** [comment]
Closing, no further action needed
