### ISSUE TITLE
Fetching Dynamic Search List

### ISSUE THREAD

**Issue by vagarwal77** [mdsol/rwslib#130]
On a eCRF, we have a DSL (Dynamic Search List) field. How, we can get list items dynamically ? 

      <ItemDef OID="AE_SAE_XX01.M_AEPID" Name="M_AEPID" DataType="text" mdsol:VariableOID="M_AEPID" Length="180" mdsol:Active="Yes" mdsol:ControlType="Dynamic SearchList" mdsol:IndentLevel="2" mdsol:SourceDocument="Yes" mdsol:SASLabel="Related AE Record" mdsol:Visible="Yes">

**Comment by isparks** [comment]
You want to get the items so that you can make a submission of a valid item? i.e. you want to get the list for the field so that you can then make a new ODM post to update the field?

As far as I know, there is no endpoint for that. You can't get it with a Rave Web Services request.

**Comment by vagarwal77** [comment]
Thanks @isparks 
Actually, as per ALS, it is executing a custom function. 
Is there a way, if we know custom function name in C#, to execute particular customer function via API?

**Comment by isparks** [comment]
Yes, in Rave you can run any custom function with the CustomFunction.PerformCustomFunction API. But there is no RWS method to call this directly.

**Comment by vagarwal77** [comment]
Thats a great news @isparks 
Unfortunately, i can not access to - 
![image](https://user-images.githubusercontent.com/46463536/150451393-4605e04c-e33a-4a85-920c-8a018dc0ab43.png)

Do you have API payload details for me to try CustomFunction.PerformCustomFunction on the same lines as below? 
https://celgsandxxx.mdsol.com/ravewebservices/datasets/VersionFoldersWithForms.odm?studyoid=XXXXXX-001Test&metadataversionoid=XXX

**Comment by isparks** [comment]
Sorry @vagarwal77, you misunderstand me. Within CustomFunction in Rave you can use CustomFunction.PerformCustomFunction to run any custom function, including Dynamic Search List CF.

But a Custom Function can only be initiated by an Edit Check and edit checks only trigger on data entry in Rave.

There is **no** https://xxx.mdsol.com/ravewebservices/run_my_custom_function endpoint

**Comment by glow-mdsol** [comment]
What he said!  If you need access to the documentation you can visit https://learn.mdsol.com and setup an iMedidata account by following the steps there.  I'm going to close this.
