### ISSUE TITLE
Record restricted by max limit

### ISSUE THREAD

**Issue by vagarwal77** [mdsol/rwslib#132]
Hi

CRF has 2 loglines pre-populated and i am trying to build clinical payload to update those loglines but getting error as below - 
RWSException error
e.rws_error.error_client_response_message - Record restricted by max limit
e.rws_error.error_origin_location - /ODM/ClinicalData[1]/SubjectData[1]/StudyEventData[1]/FormData[1]/ItemGroupData[2]
e.rws_error.reason_code - RWS00088

Please suggest what is wrong as form has 3 sections - 
1. non-logline Item Group as XXX_GEN_U01_C_PK01_S01
2. 2 logline items group as XXX_GEN_U01_C_PK01_S01_LOG_LINE

`<ODM xmlns:mdsol="http://www.mdsol.com/ns/odm/metadata" xmlns="http://www.cdisc.org/ns/odm/v1.3"
     FileType="Transactional" Granularity="Metadata" CreationDateTime="2022-03-22T13:14:35.928-00:00"
     FileOID="19c6ec03-33b8-fdfrr-8e77-667e05709c0a" ODMVersion="1.3">
    <ClinicalData StudyOID="Study-Test(DEV)" MetaDataVersionOID="1136">
        <SubjectData SubjectKey="001-1111">
            <SiteRef LocationOID="00000"/>
            <StudyEventData StudyEventOID="C1D1" StudyEventRepeatKey="C1D1[1]">
                <FormData FormOID="XXX_GEN_U01_C_PK01_S01">
                    <ItemGroupData ItemGroupOID="XXX_GEN_U01_C_PK01_S01">
                        <ItemData ItemOID="X_PCPERF_PCALL" Value="YES" />
                        <ItemData ItemOID="X_PCREASND" IsNull="Yes" />
                        <ItemData ItemOID="X_PCREASOT" IsNull="Yes" />
                        <ItemData ItemOID="X_PCREFID" Value="1234" />
                        <ItemData ItemOID="X_PCSTDAT" Value="18/MAY/2016" />
                        <ItemData ItemOID="X_PCSTTIM" Value="09:00" />
                        <ItemData ItemOID="X_PCENDAT" Value="18/MAY/2016" />
                        <ItemData ItemOID="X_PCENTIM" Value="10:30" />
                    </ItemGroupData>
                    <ItemGroupData ItemGroupOID="XXX_GEN_U01_C_PK01_S01_LOG_LINE" ItemGroupRepeatKey="@CONTEXT"
                                   TransactionType="Upsert"/>
                        <ItemData ItemOID="X_PCCAT" Value="XXXXXX" TransactionType="Upsert">                           
                        <ItemData ItemOID="X_PCTEST" Value="YYYYY" TransactionType="Upsert" />
                        <ItemData ItemOID="X_PCSPEC" Value="ZZZZZZ" TransactionType="Upsert" />
                        <ItemData ItemOID="X_PCSPID" Value="12" TransactionType="Upsert"/>
                        <ItemData ItemOID="X_PCSTAT" IsNull="Yes" TransactionType="Upsert" />
                    </ItemGroupData>
                    <ItemGroupData ItemGroupOID="XXX_GEN_U01_C_PK01_S01_LOG_LINE" ItemGroupRepeatKey="@CONTEXT"
                                   TransactionType="Upsert">
                        <ItemData ItemOID="X_PCCAT" Value="XXXXXX" TransactionType="Upsert"/>                                  
                        <ItemData ItemOID="X_PCTEST" Value="YYYYY" TransactionType="Upsert" />
                        <ItemData ItemOID="X_PCSPEC" Value="ZZZZZZ" TransactionType="Upsert" />
                        <ItemData ItemOID="X_PCSPID" Value="34" TransactionType="Upsert"/>
                        <ItemData ItemOID="X_PCSTAT" IsNull="Yes" TransactionType="Upsert" />
                    </ItemGroupData>
                </FormData>
            </StudyEventData>
        </SubjectData>
    </ClinicalData>
</ODM>`

**Comment by isparks** [comment]
Not too sure. One thing that stands out to me is that you are using ItemGroupRepeatKey="@CONTEXT" but you are not providing any context ItemData values for it to do it's lookup. The docs give an example:

```
<ODM  >
...
   <FormData FormOID="AE" FormRepeatKey="1" TransactionType="Update">
      <ItemGroupData ItemGroupOID="AE_LOGLINE" ItemGroupRepeatKey="@CONTEXT"
        TransactionType="Update">
         <ItemDataAny ItemOID="AETERM" TransactionType="Context">Headache</ItemDataAny>
         <ItemDataDate ItemOID="AESTDTC" TransactionType="Context">2010-03-14
           </ItemDataDate>
         <ItemDataDate ItemOID="AEENDTC">2010-03-20</ItemDataDate>
      </ItemGroupData>
   </FormData>
...
</ODM>
```

and 

```
In this ODM request example, the log line to be located is identified as the line where the AETERM field has the value 
Headache and the AESTDTC field has the value 2010-03-14. If both these field values are found, this request updates the 
AEENDTC field with the value 2010-03-20.
```

So the fact it can't find your log lines to update might be the problem. Could it be that its trying to create new log lines and there is a limit (set by default values with | symbol in the field default values for the log line) on the number of log lines allowed?

**Comment by glow-mdsol** [comment]
Is this resolved?  Can we close?

**Comment by vagarwal77** [comment]
Yes, please close
Thanks
