### ISSUE TITLE
Regarding list of data in the versioned CRF for a subject

### ISSUE THREAD

**Issue by rohitdev** [mdsol/rwslib#141]
Hi,
I am trying to retrieve list of forms/folders added from Medidata UI via the API.
The list of folders shown in the subject administration is not visible from the dataset API (/studies/Mediflex(Dev)/subjects/{ subjectkey }/datasets/raw). Once you save a form within one of those folders than only the forms saved would be visible. 
\Is their a way to retrieve metadata/folder added for a subject like how it appears in subject administration? The raw/regular API does not list them or is there a subject metadata API for a study which shows it?

**Comment by isparks-tg** [comment]
You want to know what folders have been added for a subject or what folders CAN BE added for a subject?

**Comment by rohitdev** [comment]
I want to know what extra folders have been added directly from the Medidata UI/web interface as well as a result of manual intervention or via edit checks.

**Comment by isparks-tg** [comment]
You could get by parsing the ODM data by subject; https://rwslib.readthedocs.io/en/latest/retrieve_clinical_data.html#subjectdatasetrequest-project-name-environment-name-subjectkey or by study (though that would be a lot of data) https://rwslib.readthedocs.io/en/latest/retrieve_clinical_data.html#studydatasetrequest-project-name-environment-name or by using the ODM adapter and looking for folder added subcategories? (https://techblog.mdsol.com/2014/12/23/reading-audit-events.html)

I don't know of an endpoint that provides what you are looking for in an easy manner, there is no SubjectFolders API that I know of.

**Comment by rohitdev** [comment]
Thanks for the reply Ian and this detail.
If have to be more precise I am looking for API capabilities to manage and read changes done on the subject administration screen in Medidata. You can add folders and other matrices which deviate from the pre defined structure in ALS.

**Comment by isparks-tg** [comment]
Yes, I think this is something that the sites find quite useful at times but which is a headache for integrators. You could try talking to Medidata but I think the best approach, if you want to stick to API's available on all Rave URLs is to use the ODM Adapter aka ClinicalAuditRecords dataset. It's a log of all actions that happen in the study taken from the Rave audit trail. You should look for audit records related to Instances (rave's name for subject Folders). 

If you have access to the Rave knowlege base then this page explains it: https://learn.medidata.com/en-US/bundle/rave-web-services/page/retrieve_clinical_data_with_the_clinical_audit_records_dataset.html - if you don't, one of your clients should have access and may be able to help you. It's the same thing from the ancient blog post I posted before. I don't know for sure that folders added from subject admin (or by edit check, another source of potential off-the-books folders) will be in the dataset but if its in the audit trail in Rave then you would expect to see it in the output.

**Comment by rohitdev** [comment]
Thanks a bunch Ian! Helps a lot to logically conclude the further course of action.
