### ISSUE TITLE
Study Does Not Exist error should be an Auth error

### ISSUE THREAD

**Issue by hamotoJohn** [mdsol/rwslib#21]
When querying through the StudyVersionRequest for a study that definitely exists, I get a Study Does Not Exist error. It seems that I haven't been given Architect rights in that study (querying the /metadata/studies url yields no studies listed, but the /studies url, ie ClinicalStudiesRequest, yields two studies).

The Does Not Exist error is misleading (I spent time trying to figure out how I'd mistyped or mis-encoded the name). It should have returned an authorization error.

**Comment by isparks** [comment]
Hi @hamotoJohn, thanks for trying rwslib.

Unfortunately RWS returns a DoesNotExist error code and so rwslib doesn't know that this is an auth error. I believe the idea is to reduce the chance of attackers trying likely study names until they get an auth error and then user/password guessing. I will add a note to the docs on this.

**Comment by hamotoJohn** [comment]
That seems reasonable. (I guess I have questions now about throttling and whatnot...)

**Comment by isparks** [comment]
Regarding throttling, quotas etc: Currently Rave and RWS do not impose any besides some limitations on how long a connection will be held open (limiting very large downloads) and how long the firewall will allow a connection to be held before it gets the first byte of response. We do have automated monitoring and if we see something that looks inefficient/abusive we will try to work with you on it.
