### ISSUE TITLE
innovate backend seems not compatibile with rwslib

### ISSUE THREAD

**Issue by dPeS** [mdsol/rwslib#49]
Hi all,

when I do this:

r.send_request(AuditRecordsRequest('Mediflex', 'DEV', per_page=**1000000**, startid=**1**))
->
https://innovate.mdsol.com/RaveWebServices/datasets/ClinicalAuditRecords.odm?studyoid=Mediflex%28DEV%29&startid=1&per_page=1000000
->
{'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Set-Cookie': 'MedidataRave=1946950572.20480.0000; path=/', 'X-AspNet-Version': '4.0.30319', 'Vary': 'Accept-Encoding', 'X-Powered-By': 'ASP.NET', 'Server': 'Microsoft-IIS/7.5', 'Link': '<https://innovate.mdsol.com/RaveWebServices/datasets/ClinicalAuditRecords.odm?studyoid=Mediflex%28DEV%29&startid=8256305&per_page=1000000>; rel="next"', 'X-AspNetMvc-Version': '3.0', 'Cache-Control': 'private, s-maxage=0', 'Date': 'Wed, 13 Apr 2016 07:42:36 GMT', 'Content-Type': 'text/xml'}

startid is not taken into account I think,
Thanks
d.

**Comment by isparks** [comment]
Hi d,

The Audit table for a rave installation contains all audit records for all studies. So audit record ID=1 might belong to StudyA, ID=2 might belong to StudyB. When you ask "starting at record 1" that means the place to start the search. It might not find any records related to Mediflex (DEV) until record 100,000. In fact, in this case it returns you some records and then tells you to continue the search from startid=8256305 which is where it left off looking for records.

You probably found that you didn't get back 1,000,000 records, one thousand is more likely. If you ask for too many you'll a) put additional strain on the Rave server (possibly leading to performance issues for Rave users) and b) risk a timeout from our hosting inffrastructure which will cause you to get a truncated response.

Hope that helps.

**Comment by dPeS** [comment]
Hi, 

Thanks a lot for fast reply!

My base case here is: to track audit log for StudyA. Questions:

how to get >first< ID for particular study?

why when put startid=1 and per_page=1000 I get **56** rows
when per_page=10000 -> **56** rows
when per_page=100000 -> **148** rows (all for that test study)

don't want to fetch all events since it's not scalable

**Comment by isparks** [comment]
Hi,

Best way is to start at 1. Ask for 1,000 records. In the headers of the response you get back you already saw : 

'Link': 'https://innovate.mdsol.com/RaveWebServices/datasets/ClinicalAuditRecords.odm?studyoid=Mediflex%28DEV%29&startid=8256305&per_page=1000000; rel="next"'

So then you make another request, startid=8256305 asking for 1000 records and so on until you get back an empty response, no more records. 

The docs on the rwslib request are here:

http://rwslib.readthedocs.org/en/latest/odm_adapter.html#auditrecordsrequest-project-name-environment-name

And more information about the service itself is here:

https://learn.mdsol.com/display/RWSprd/About+the+RWS+Operational+Data+Model+%28ODM%29+Adapter#AbouttheRWSOperationalDataModel(ODM)Adapter-RetrievingClinicalDataAudits

You might also find the audit_event helper class useful for your use case. Take a look at:

https://github.com/mdsol/rwslib/tree/develop/rwslib/extras/audit_event

It is part of rwslib in the extras package.

Interested to know who you are and what you are doing. If we can help contact me at isparks@mdsol.com.

**Comment by dPeS** [comment]
Great! this is a little bit confusing but it works! :) audit_event code is also interesting. I've read whole docs before. Placing the example in docs would be very convenient for future users don't you think?

Thanks!

**Comment by isparks** [comment]
I'll add a link to the audit_event code in the docs in future, thanks for using rwslib.
