### ISSUE TITLE
OrderNumber should be optional on ItemGroupRef

### ISSUE THREAD

**Issue by anewbigging** [mdsol/rwslib#92]
https://rwslib.readthedocs.io/en/latest/classes.html#rwslib.builders.ItemGroupRef

order_number is a required parameter, but its optional on ItemGroupRef according to the ODM standard, and its not included when extracting study metadata from Rave via RWS, so it should be optional on the builder as well.

**Comment by glow-mdsol** [comment]
Updating in the next release

**Comment by glow-mdsol** [comment]
Closed as updated
