### ISSUE TITLE
OrderNumber should be optional on StudyEventRef SUBJECT and optional on StudyEventDef

### ISSUE THREAD

**Issue by anewbigging** [mdsol/rwslib#93]
When extracting metadata from RWS the SUBJECT StudyEventRef has no OrderNumber (which makes sense since this is an 'artificial' folder, not created by the study designer but there to allow subject-level forms to be specified in the corresponding StudyEventDef).  It would be nice if the builders allowed this, but at the moment OrderNumber is required on the StudyEventRef (https://rwslib.readthedocs.io/en/latest/classes.html#rwslib.builders.StudyEventRef).

The StudyEventDef builder does not have an OrderNumber attribute but RWS does export OrderNumber on StudyEventDefs (except the SUBJECT one):

```
     <Protocol>
        <StudyEventRef StudyEventOID="SUBJECT" Mandatory="Yes" />
        <StudyEventRef StudyEventOID="SCREEN" OrderNumber="1" Mandatory="No" />
      </Protocol>
      <StudyEventDef OID="SUBJECT" Name="Subject" Type="Common" Repeating="No">
        <FormRef FormOID="VISIT" OrderNumber="3" Mandatory="No" />
      </StudyEventDef>
      <StudyEventDef OID="SCREEN" Name="Screening" Type="Common" Repeating="Yes" mdsol:OrderNumber="1">
        <FormRef FormOID="VISIT" OrderNumber="3" Mandatory="No" />
```

**Comment by glow-mdsol** [comment]
Thanks; Are you contemplating using the builders for deserialising the output of RWS Study Metadata?  That would be cool.  I'll make the `OrderNumber` lazy
